### ISSUE TITLE
We need You!

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/v2ray-rust#1]
This is expected to be a huge project. We're in great need of more experts on related fields.
Feel free to leave comments down here!

**Comment by whizsid** [comment]
I would like to work on[configuration JSON file](https://www.v2fly.org/en_US/config/overview.html) parsing. I will send a PR.

**Comment by darsvador** [comment]
**Router** related algorithm has been completed.
[CIDRMatcher](https://github.com/Qv2ray/CIDRMatcher)
[DomainMatcher](https://github.com/Qv2ray/DomainMatcher)

**Comment by ghost** [comment]
There are some previous attempts around.

https://github.com/eycorsican/leaf
<-- this is pretty good actually.  Even better than v2ray-go in proxySettings (proxy chains), and balancing based on speed test.

https://github.com/p4gefau1t/trojan-r

**Comment by DuckSoft** [comment]
> There are some previous attempts around.
> 
> https://github.com/eycorsican/leaf
> <-- this is pretty good actually. Even better than v2ray-go in proxySettings (proxy chains), and balancing based on speed test.
> 
> https://github.com/p4gefau1t/trojan-r

In fact, we are different in some ways. `leaf` is using `tokio` while we are using `smol`, and `trojan-r` don't have routing by design.
We are trying to offer a limitedly-compatible V2Ray while the infrastructure is refined.

Of course, we tend to gugugu.
