### ISSUE TITLE
no utls?

### ISSUE THREAD

**Issue by flyysquirrel** [Qv2ray/v2ray-rust#163]
```
[[inbounds]]
addr = '0.0.0.0:12333'
tag = 'http-in-1'

[[inbounds]]
addr = '0.0.0.0:1089'
enable_udp = true
tag = 'socks-in-1'

[[outbounds]]
chain = [ 'sni', 'trojan' ]
tag = 'Default'

[[tls]]
sni = 'yoursni.com'
tag = 'sni'

[[trojan]]
addr = 'example.com:443'
password = 'example_password'
tag = "trojan"
```

my test result: 
https://tlsfingerprint.io/id/9c673fd64a32c8dc

**Comment by darsvador** [comment]
Please express your question clearly. uTLS is a golang library, it is impossible to import it as a dependency. Currently, we are imitating the TLS fingerprint of chromium.

**Comment by flyysquirrel** [comment]
So what's the fingerprint of chromium?
Could you please give the link?

**Comment by darsvador** [comment]
It seems we are imitating an older chromium TLS fingerprint. The latest chromium TLS fingerprint is [e47eae8f8c4887b6](https://tlsfingerprint.io/id/e47eae8f8c4887b6). I have updated the TLS fingerprint in eefa91ea78c4a7b6294d7d09494706e4e801ebfb. Thank you for your report.

**Comment by flyysquirrel** [comment]
It works well, thx
