### ISSUE TITLE
How about update the ssl fingerpoint with time?

### ISSUE THREAD

**Issue by Johnshall** [Qv2ray/v2ray-rust#8]
Dear developers,
Hello!
I have read https://github.com/Qv2ray/v2ray-rust/commit/35cce0fd2664b428e1772b44d3867d9b18415541 and in this commit we resistance the ClientHello fingerprinting by imitating a certion version of chromium tls fingerprint. With the time went by and the updating of chromeium, It could be detected as a fingerprint of v2ray-rust.
Therefore, we could change `SSLVersion,Cipher,SSLExtension,EllipticCurve,EllipticCurvePointFormat` by workflow to update them with the newest chromium.
I think it could be helpful. Thanks for your work!

**Comment by darsvador** [comment]
To imitate the Chromium fingerprint, one should read the Chromium source and check the new fingerprint whether it's a commonly used fingerprint. This is very difficult for workflow. Also, I don't think it's a good idea to modify the source code via workflow.

**Comment by Johnshall** [comment]
Yeal, you are right. I agree with you. I think this commit is essential for this project when it has a lot of users.
If you are interested in this commit, we could discuss the solution in detail.
There could be three parts in these jobs:

1. Bring the settings of `SSLVersion,Cipher,SSLExtension,EllipticCurve,EllipticCurvePointFormat` into a configuration file in json/yaml or other format.
2. Get Chromium fingerprint from Chromium source and write into the file above.
3. Test that whether it is a commonly used fingerprint.

I think job 2 and 3 are easy to be done in python by workflow. I could undertake these parts of the task. But I'm not good at rust (Just learning) and there are too many complex dependences to be understood. If it is convenient for you, we could work together to make this project better.

Thanks for your work and patience.

**Comment by darsvador** [comment]
boring-ssl does not implement all the APIs of OpenSSL. For example, `SSL_CTX_set_ciphersuites`. So, it is not realistic to provide fully configurable TLS. And when you use OpenSSL you can't even imitate the behavior of boring-ssl. Maybe you can take a look at how chromium uses boring-ssl: https://github.com/chromium/chromium/blob/main/net/socket/ssl_client_socket_impl.cc.

**Comment by darsvador** [comment]
I guess we can close this since there is no further update.
